version: 2.1

orbs:
  node: circleci/node@4.5.0
  browser-tools: circleci/browser-tools@1.1.3

commands:
  build-tape:
    description: "Build tapejs"
    steps:
      - run: npm run build-tape
  test:
    description: "Running tests"
    steps:
      - run: npm run test
  chrome-version:
    description: "Show Chrome's version"
    steps:
      - run: google-chrome --version

workflows:
  test:
    jobs:
      - install-chrome
      - build-and-test

jobs:
  install-chrome:
    docker:
      - image: 'cimg/node:13.12-browser'
        auth:
          username: imnutz
          password: $DOCKER_PWD
    steps:
      - browser-tools/install-chrome
      - chrome-version

  build-and-test:
    executor:
      name: node/default
      tag: '13.12'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - build-tape
      - test

