version: 2.1

orbs:
  node: circleci/node@4.5.0

commands:
  build-tape:
    description: "Build tapejs"
    steps:
      - run: npm run build-tape
  test:
    description: "Running tests"
    steps:
      - run: npm run test

workflows:
  test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '15.1'
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - build-tape
      - test

