version: 2.1

orbs:
  node: circleci/node@4.5.0
  browser-tools: circleci/browser-tools@1.1.3

commands:
  build-tape:
    description: "Build tapejs"
    steps:
      - run: npm run build-tape
  test:
    description: "Running tests"
    steps:
      - run: npm run test

workflows:
  test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:13.12-browser'
    executor:
      name: node/default
      tag: '13.12'
    steps:
      - browser-tools/install-chrome
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - build-tape
      - test

