version: 2.1

orbs:
  node: circleci/node@4.5.0
  browser-tools: circleci/browser-tools@1.1.3

commands:
  build-tape:
    description: "Build tapejs"
    steps:
      - run: npm run build-tape
  test:
    description: "Running tests"
    steps:
      - run: npm run test
  chrome-version:
    description: "Show Chrome's version"
    steps:
      - run: google-chrome --version

workflows:
  test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: 'cimg/node:15.14.0-browsers'
        auth:
          username: imnutz
          password: $DOCKER_PWD
    executor:
      name: node/default
      tag: '15.14.0'
    steps:
      - browser-tools/install-chrome
      - chrome-version
      - checkout
      - node/install-packages:
          override-ci-command: npm install
      - save_cache:
            paths:
              - ~/project/node_modules  # location depends on npm version
            key: rwce-{{ .Branch }}-{{ checksum "package-lock.json" }}

      - build-tape
      - test

