version: 2.1

orbs:
  node: circleci/node@4.5.0

commands:
  build-tape:
    description: "Build tapejs"
    steps:
      - run: npm build-tape
  test:
    description: "Running tests"
    steps:
      - run: npm test

workflows:
  test:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker: 
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packags
      - build-tape
      - test

